## Gateway Config
spring.application.name=est-gateway-v2
## SSL Server
server.port=8888
server.http2.enabled=true
server.ssl.enabled=true
server.ssl.key-alias=maestro
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:maestro.jks
server.ssl.key-store-password=123456
server.ssl.trust-certificate-private-key=classpath:maestro.pem
## Cloud Gateway 
spring.cloud.gateway.server.webflux.httpclient.ssl.trusted-x509-certificates=classpath:maestro.crt
spring.cloud.gateway.server.webflux.httpclient.ssl.key-password=123456
spring.cloud.gateway.server.webflux.httpclient.ssl.key-store=classpath:maestro.jks
spring.cloud.gateway.server.webflux.httpclient.ssl.key-store-type=PKCS12
